### ISSUE TITLE
🐛 [Bug] The new development version causes most eluna scripts to break

### ISSUE THREAD

**Issue by Greyisttot** [Eluna-Ports/Eluna-VMaNGOS#4]
player:SendBroadcastMessage
RegisterPlayerEvent(32, OnLootItem)
RegisterPlayerEvent(25, Save)
...

**Comment by Greyisttot** [comment]
local function OnLootItem(event, player, item, count)
    SendWorldMessage("...")
end

RegisterPlayerEvent(32, OnLootItem)

**Comment by Greyisttot** [comment]
local function Save(event, player)
    SendWorldMessage("...")
end

RegisterPlayerEvent(25, Save)

**Comment by Niam5** [comment]
Hook 25 wasn't implemented previously it is now and hook 32 has been moved to the correct placement to trigger. Fixed in 2afc4589dc5d64f1f3bf18ccd85b99d6b81ccfc6.
