### ISSUE TITLE
🐞 [Bug] player:RemoveItem(item, count)

### ISSUE THREAD

**Issue by Greyisttot** [Eluna-Ports/Eluna-VMaNGOS#5]
local function OnLootItem(event, player, item, count)
    player:RemoveItem(item, count)
end

RegisterPlayerEvent(32, OnLootItem)

**Comment by Greyisttot** [comment]
local function OnLootItem(event, player, item, count)
    local GetEntry = item:GetEntry()
    local GetCount = item:GetCount()
    local SellPrice = item:GetSellPrice()
    --player:ModifyMoney(SellPrice)
    player:RemoveItem(GetEntry, GetCount)
    player:SendBroadcastMessage(" " .. GetCount .. " ")
end

RegisterPlayerEvent(32, OnLootItem)

**Comment by Greyisttot** [comment]
16:01:02 ./mangosd(_ZN6Player11SendNewItemEP4Itemjbbbb+0x162) [0x55fb8b31d842]
./mangosd(_ZN12WorldSession29HandleAutostoreLootItemOpcodeER11WorldPacket+0x377) [0x55fb8b20ad17]
./mangosd(_ZN12WorldSession13ExecuteOpcodeERK13OpcodeHandlerP11WorldPacket+0x6f) [0x55fb8b0ae0ef]
./mangosd(_ZN12WorldSession14ProcessPacketsER12PacketFilter+0x2cf) [0x55fb8b0b116f]
./mangosd(_ZN12WorldSession6UpdateER12PacketFilter+0x3b) [0x55fb8b0b3c7b]
./mangosd(_ZN3Map6UpdateEj+0x12b) [0x55fb8b24346b]
./mangosd(_ZN10ThreadPool9worker_sq6doWorkEv+0x54) [0x55fb8b7c44e4]
./mangosd(_ZN10ThreadPool6worker4loopEv+0xd6) [0x55fb8b7c5496]
/lib/x86_64-linux-gnu/libstdc++.so.6(+0xdc253) [0x7f7d560f2253]
/lib/x86_64-linux-gnu/libc.so.6(+0x94ac3) [0x7f7d55d7aac3]
/lib/x86_64-linux-gnu/libc.so.6(+0x126850) [0x7f7d55e0c850]

Segmentation fault (core dumped)

**Comment by Niam5** [comment]
A reposition of the onloot has been pushed, try that and see if you still get the crash. If you do it may be related to how vmangos handles threading/subthreading.

**Comment by Niam5** [comment]
Also provide COMPLETE scripts you are using not just select portions. Without the FULL script I will not be providing assitance.
