### ISSUE TITLE
🐛 [Bug]When mangosd.exe reads the group and group_member tables, it crashes and must be cleared before it can start

### ISSUE THREAD

**Issue by leechunlung** [Eluna-Ports/Eluna-VMaNGOS#7]
### Steps to reproduce

1.When mangosd.exe reads the group and group_member tables, it crashes and must be cleared before it can start
2.mangosd.conf set "AllowTwoSide.Interaction.Group = 1",and It contains team formation data for alliances and Horde
3.The original build no errors
4. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Niam5** [comment]
Unable to reproduce. Provide more detail. You can help by building the server from source in debug mode and attach a debugger to get more output.
